In [13]:
import numpy as np

In [53]:
# 1.a
range_array = np.arange(1, 11)
print(range_array)
# 1.b
steps_range_array = np.arange(0.5, 5 + 0.25, 0.25)
print(steps_range_array)

[ 1  2  3  4  5  6  7  8  9 10]
[0.5  0.75 1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.   3.25 3.5  3.75
 4.   4.25 4.5  4.75 5.  ]


In [79]:
# 2.a
print(np.zeros(10, dtype=int))
# 2.b
print(np.zeros((3,4), dtype=int))

[0 0 0 0 0 0 0 0 0 0]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [81]:
# 3.a
lin_array = np.linspace(2, 12, 5, dtype=int)
print(lin_array)
# 3.b
lin_array_s = np.linspace(3, 9, 4, dtype=int)
print(lin_array_s)

[ 2  4  7  9 12]
[3 5 7 9]


In [134]:
# 4.a
random_array = np.random.rand(4, 2)
print(random_array)
# 4.b
random_int = np.random.randint(10, 21, (3, 3))
print(random_int)
# 
reshapred = random_array.reshape(1, 8)
print(reshapred)
# 
# When using reshapred function, we need to make sure that the array you are reshaping has the right amount of numbers for the new shape

[[0.14477073 0.69606886]
 [0.06490733 0.8834079 ]
 [0.78122905 0.48877598]
 [0.03751328 0.92207972]]
[[15 10 16]
 [20 13 16]
 [17 14 17]]
[[0.14477073 0.69606886 0.06490733 0.8834079  0.78122905 0.48877598
  0.03751328 0.92207972]]


In [ ]:
# 5
# If we draw random numbers by using seed function, the same numbers will be drawn every time we will run the function.

# The advantage of this is that if we want to use the same random numbers for different purposes, 
# for example: to train the model then we don't have to keep a big list of numbers and load it every time. 
# In addition, if we want to add values, the seed function will keep the previous values and add new random values and this will avoid the need to update new values every time when working with a list.

In [142]:
# 6.a
user_list = []
for _ in range(5):
    num = int(input("Enter a number: "))
    user_list.append(num)
# b
numbers_array = np.array(user_list)
# c
print('max', numbers_array.max())  
# d
print('min', numbers_array.min()) 
# e
print('shape', numbers_array.shape)
# f
print('argmax', numbers_array.argmax())
# g
print('argmin', numbers_array.argmin())

Enter a number:  2
Enter a number:  4
Enter a number:  6
Enter a number:  8
Enter a number:  10


max 10
min 2
shape (5,)
argmax 4
argmin 0
